### PR TITLE
Add 32-bit interger and number

### PR DESCRIPTION
**Pull request by jadr2ddude**

### CODE REVIEW

**Comment by dibyendumajumdar** [comment]
Hi I had a quick look at your changes. I think there may be more areas that need to be checked/changed - for example making sure that the layout of Lua objects between C code and LLVM is the same, etc. Any place where C_doubleT is used will need to be checked. Also the libgccjit implementation will need to be updated. Keeping integer and floating point sizes same does simplify things of course. 

I think the tbaa structures should be fine as they are as they are really just to help LLVM optimizer.

Have you successfully run the tests when linked with LLVM? You can go to lua_tests folder and say run_tests.sh <your ravi binary>.

**Comment by jadr2ddude** [comment]
I haven't been able to link it with llvm on 32 bit. It doesn't seem to want to link with /usr/lib32 on a 64 bit system. Did you add your own flag for lib path?

**Comment by dibyendumajumdar** [comment]
I build LLVM from source
From: jadr2ddude
Sent: Sunday, 3 July 2016 9:34 PM
To: dibyendumajumdar/ravi
Reply To: dibyendumajumdar/ravi
Cc: Dibyendu Majumdar; Comment
Subject: Re: [dibyendumajumdar/ravi] Add 32-bit interger and number (#93)



I haven't been able to link it with llvm on 32 bit. It doesn't seem to want to link with /usr/lib32 on a 64 bit system. Did you add your own flag for lib path?

-

**Comment by dibyendumajumdar** [comment]
I build LLVM from source and explicitly specify the LLVM_DIR to CMake.

**Comment by jadr2ddude** [comment]
Ok then maybe we need to add an option to use an existing compilation

**Comment by jadr2ddude** [comment]
Just tested it and it works on 32-bit and 64-bit!

**Comment by jadr2ddude** [comment]
Might want to add a 32-bit travis test.

**Comment by dibyendumajumdar** [comment]
Great, thanks! I will test this over the next few days and merge. 
Thank you very much for taking the time to do this.

**Comment by jadr2ddude** [comment]
No prob.

**Pull request closed without merging**
