### PR TITLE
Remove the need for std::atomic and make it compile on arm linux.

### PR DESCRIPTION
**Pull request by mingodad**

### CODE REVIEW

**Comment by dibyendumajumdar** [comment]
Thanks. I don't like the idea of relying upon a static constructor - maybe we could just ignore the multiple initialization issue as LLVM says its okay? If you could undo the static constructor I will merge the changes in.

**Comment by mingodad** [comment]
Hello !
For me I'll leave as it is for now but you can merge manually the rest if you find suitable (it's not a big patch). The original implementation using atomic increments have a undesired side effect of rolling back for long execution programs (I mean the counters will become 0,1,2,3,... eventually).
Or as you said for the initialization call it every time.

By the way I came to your project because I'm trying to implement something like this plus Cxx.jl (https://gist.github.com/mingodad/99d34ad93f59def5ad0ee809681be0e1) and also Terra (https://github.com/zdevito/terra).

Like you said in your presentation luajit is very good but hard to change/extend. I want to apply this to my fork of Squirrel scripting language called SquiLu (https://github.com/mingodad/squilu).
Cheers !

**Comment by mingodad** [comment]
And maybe you didn't noticed but you already have static constructor in the actual code (direct added by you and indirect by C++ libaries).
Example :
```
static std::atomic_int init;
static std::atomic_int module_id;
```
The above are in fact class instantiations.
Cheers !

**Comment by dibyendumajumdar** [comment]
I will check whether the static initialization of std::atomic types provide any additional guarantees by the compiler. I think using the module's address as the id is better than using an integer id so happy with that, but I am not sure about the init change.

Do you need the atomic change removal for ARM or is this unrelated?

Wish you success with squilu!

**Comment by mingodad** [comment]
No for the ARM compilation (raspberry pi) only the CMakeLists.txt is needed.

**Pull request merged**
