### PR TITLE
Improve type deduction for cond and x or y

### PR DESCRIPTION
**Pull request by XmiliaH**
Allow type deduction for `cond and x or y` when x and y are of the same type or numbers.

### CODE REVIEW

**Comment by dibyendumajumdar** [comment]
hi, do you think we should change the values assigned to the enum so that it is like Lua does - i.e. numbers have a common bit, and a variant bit? Similarly table, integer array and float array? Also should we split out true and false like its done in LuaJIT / Lua 5.4?

**Comment by dibyendumajumdar** [comment]
btw I liked your previous PR more because it was more generic I felt. Although it posed a problem because of the impact on my other compiler work - I do think maybe it is the better way forward. Maybe we need to first do a step that sorts out the type information and how it is used. Then the actual type deduction improvement can follow. What do you think?

**Comment by XmiliaH** [comment]
I too like the other, more generic way more. Therefore I implemented it first instead of this approach.

**Comment by dibyendumajumdar** [comment]
Okay lets go back to that then? I don't know if you want to refresh it or leave it with me ...

**Comment by XmiliaH** [comment]
I didn't look into the compiler part yet. So I would currently leave it with you.

**Comment by dibyendumajumdar** [comment]
Okay - I will work on that. I merged it to a branch so that I can revise it before merging to master

**Comment by dibyendumajumdar** [comment]
Hi @XmiliaH  please review https://github.com/dibyendumajumdar/ravi/tree/new_type_info

**Comment by XmiliaH** [comment]
I would bump the version of the binary format due to the change from byte to integer. Maybe also allow to load older versions with a mapping from the old values to the new ones.

**Pull request closed without merging**
